spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/obe
    username: root
    password: root
  session:
    jdbc:
      initialize-schema: always

  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    check-template-location: false
server:
  port: 6060